CREATE SCHEMA IF NOT EXISTS identity;
CREATE TABLE IF NOT EXISTS identity.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  full_name varchar(255) NOT NULL,
  role varchar(50) NOT NULL DEFAULT 'learner',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT users_role_check CHECK (role IN ('learner','admin'))
);
CREATE TABLE IF NOT EXISTS identity.user_profiles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL UNIQUE REFERENCES identity.users(id) ON DELETE CASCADE,
  phone varchar(50), bio text, education varchar(255), work_experience_years integer NOT NULL DEFAULT 0,
  prior_training text, designation varchar(255), department varchar(255), job_role varchar(255),
  current_assignment text, areas_of_interest text, language_pref varchar(20) NOT NULL DEFAULT 'en',
  appearance_pref varchar(20) NOT NULL DEFAULT 'light', profile_pic_url varchar(500),
  onboarding_completed boolean NOT NULL DEFAULT false, daily_goal_minutes integer NOT NULL DEFAULT 30,
  current_streak_days integer NOT NULL DEFAULT 1, last_active_date timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS identity.departments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL UNIQUE,
  description text
);
