import Link from "next/link";
import { ArrowRight, BarChart3, BookOpen, Brain, Calculator, ChartNoAxesColumnIncreasing } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata = { title: "Statistical Competency | iGOT Karmayogi", description: "Practice official price-statistics methods through adaptive, verified assessments." };
const topics = [[Calculator, "Price indices", "Price relatives, CPI weights, Laspeyres and Fisher indices."], [BarChart3, "Interpret official data", "Read CPI trajectories and weighted-contribution charts."], [Brain, "Adaptive practice", "Receive a next question matched to your demonstrated mastery."]] as const;

export default function StatisticalCompetencyHubPage() {
  return <main className="min-h-[calc(100vh-68px)] bg-[#F8FAFC]"><section className="hero-gradient relative overflow-hidden py-14 text-white sm:py-20"><div className="hero-mesh absolute inset-0 opacity-40" /><div className="relative mx-auto max-w-6xl px-4 sm:px-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">MoSPI · Statistical capacity building</p><h1 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-5xl">Build confidence with official statistics.</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-white/75 sm:text-base">Learn the methods behind price statistics, then practise with a short adaptive assessment that explains every result.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/statistical/exam"><Button size="lg" className="bg-white font-bold text-[#1E3A8A] hover:bg-slate-100">Start adaptive practice <ArrowRight className="ml-2 size-4" /></Button></Link><Link href="/courses/2" className="text-sm font-semibold text-white/85 hover:text-white">View CPI course</Link></div></div></section><section className="mx-auto grid max-w-6xl gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[1.3fr_0.7fr] lg:py-14"><div><h2 className="text-xl font-bold tracking-tight text-slate-950">A focused learning path</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-600">Start with a question. The assessment keeps calculations and answers server-validated, while chart items build practical reading skills.</p><div className="mt-6 grid gap-3 sm:grid-cols-3">{topics.map(([Icon, title, description]) => <article key={title} className="rounded-xl border border-slate-200 border-l-4 border-l-[#1E3A8A] bg-white p-4 shadow-sm"><Icon className="size-5 text-[#1E3A8A]" /><h3 className="mt-4 text-sm font-bold text-slate-900">{title}</h3><p className="mt-1 text-xs leading-relaxed text-slate-600">{description}</p></article>)}</div></div><aside className="rounded-2xl border border-amber-200 bg-amber-50/70 p-5"><ChartNoAxesColumnIncreasing className="size-5 text-amber-700" /><h2 className="mt-3 text-base font-bold text-slate-950">Prefer to explore first?</h2><p className="mt-2 text-sm leading-relaxed text-slate-700">Browse the statistical catalogue and return to the assessment when you are ready.</p><Link href="/discover?category=statistical" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#1E3A8A] hover:underline"><BookOpen className="size-4" />Browse courses</Link></aside></section></main>;
}
