import Link from "next/link";
import { ArrowRight, BookOpen, LockKeyhole, ShieldAlert, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata = { title: "Digital Governance & Cybersecurity | iGOT Karmayogi", description: "Practice public-sector cyber response and digital-governance decisions." };
const pathways = [[ShieldAlert, "Cyber sandbox", "Investigate evidence and complete guided defensive labs.", "/digital-governance/sandbox"], [ShieldCheck, "Decision scenarios", "Make decisions through realistic public-sector incident briefings.", "/digital-governance/scenarios"]] as const;

export default function DigitalGovernanceHubPage() {
  return <main className="min-h-[calc(100vh-68px)] bg-[#F8FAFC]"><section className="hero-gradient relative overflow-hidden py-14 text-white sm:py-20"><div className="hero-mesh absolute inset-0 opacity-40" /><div className="relative mx-auto max-w-6xl px-4 sm:px-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">MeitY · CERT-In · Digital governance</p><h1 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-5xl">Make secure decisions for public services.</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-white/75 sm:text-base">Work through practical incident response and governance exercises built around the responsibilities of public institutions.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href="/digital-governance/scenarios"><Button size="lg" className="bg-white font-bold text-[#1E3A8A] hover:bg-slate-100">Start a decision scenario <ArrowRight className="ml-2 size-4" /></Button></Link><Link href="/discover?category=digital-governance" className="text-sm font-semibold text-white/85 hover:text-white">Browse courses</Link></div></div></section><section className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:py-14"><h2 className="text-xl font-bold tracking-tight text-slate-950">Choose one way to practise</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">Both paths build the same core competencies. Start with a decision scenario for guided practice, or move directly to evidence-led lab work.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{pathways.map(([Icon, title, description, href]) => <Link key={title} href={href} className="group rounded-2xl border border-slate-200 border-l-4 border-l-[#1E3A8A] bg-white p-6 shadow-sm transition hover:border-[#1E3A8A] hover:shadow-md"><Icon className="size-6 text-[#1E3A8A]" /><h3 className="mt-5 text-lg font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#1E3A8A]">Open workspace <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link>)}</div><div className="mt-8 flex items-center gap-3 rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-600"><LockKeyhole className="size-5 shrink-0 text-[#1E3A8A]" /><span>Practice covers incident handling, privacy, cloud governance, digital signatures, and public digital infrastructure.</span><Link href="/discover?category=digital-governance" className="ml-auto hidden shrink-0 items-center gap-1 font-semibold text-[#1E3A8A] hover:underline sm:inline-flex"><BookOpen className="size-4" />Courses</Link></div></section></main>;
}
